# Generated by Django 3.0.7 on 2020-07-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mytag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=127)),
                ('body', models.CharField(max_length=31)),
                ('period', models.CharField(max_length=31)),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
    ]
