# Generated by Django 3.0.7 on 2020-07-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='quote',
            name='body',
            field=models.CharField(max_length=127),
        ),
    ]
