# Generated by Django 3.0.7 on 2020-09-02 20:29

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('api', '0009_auto_20200902_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='etags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
