# Generated by Django 3.0.7 on 2020-09-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_profile_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
