# Generated by Django 3.0.7 on 2020-09-20 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_topic_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.URLField(max_length=255),
        ),
        migrations.CreateModel(
            name='MyNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=127)),
                ('time', models.DateTimeField()),
                ('body', models.TextField()),
                ('file', models.URLField(max_length=511)),
                ('file_type', models.CharField(choices=[('IMG', 'Image'), ('VID', 'Video')], default='IMG', max_length=7)),
                ('newsAgency', models.CharField(max_length=63)),
                ('source', models.URLField(max_length=255)),
                ('pos', models.IntegerField(default=0)),
                ('neg', models.IntegerField(default=0)),
                ('clickable', models.BooleanField(default=True)),
                ('visibility', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='api.Category')),
                ('etags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('tags', models.ManyToManyField(to='api.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
