# Generated by Django 3.0.7 on 2020-09-20 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_auto_20200920_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='file_type',
            field=models.CharField(choices=[('IMG', 'Image'), ('VID', 'Video')], default='IMG', max_length=7),
        ),
        migrations.AddField(
            model_name='news',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MyNews',
        ),
    ]
