# Generated by Django 3.0.7 on 2020-09-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200920_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsAgency',
            field=models.CharField(blank=True, default=None, max_length=512),
        ),
    ]
