# Generated by Django 3.0.7 on 2020-09-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200920_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsAgency',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
