# Generated by Django 3.0.7 on 2020-09-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200920_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='independent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsAgency',
            field=models.CharField(default='h', max_length=512),
            preserve_default=False,
        ),
    ]
